export const DEVICES = [
  {
    id: "iphone-mail",
    name: "iPhone Mail",
    subjectCharsJa: 18,
    subjectCharsEn: 38,
    previewCharsJa: 0,
    previewCharsEn: 0,
    senderChars: 15,
    type: "mobile",
    chrome: {
      unread: "dot",
      avatar: true,
      avatarSize: 36,
      avatarRadius: "22%",
      chevron: true,
      star: false,
      senderFont: 13,
      subjectFont: 12,
      previewFont: 11,
      rowPadding: "10px 12px",
      contentGap: 10,
    },
  },
  {
    id: "iphone-gmail",
    name: "iPhone Gmail",
    subjectCharsJa: 17,
    subjectCharsEn: 32,
    previewCharsJa: 22,
    previewCharsEn: 45,
    senderChars: 14,
    type: "mobile",
    chrome: {
      unread: "bold",
      avatar: true,
      avatarSize: 36,
      avatarRadius: "50%",
      chevron: false,
      star: true,
      senderFont: 13,
      subjectFont: 12,
      previewFont: 11,
      rowPadding: "10px 12px",
      contentGap: 10,
    },
  },
  {
    id: "android-gmail",
    name: "Android Gmail",
    subjectCharsJa: 18,
    subjectCharsEn: 35,
    previewCharsJa: 24,
    previewCharsEn: 48,
    senderChars: 16,
    type: "mobile",
    chrome: {
      unread: "bold",
      avatar: true,
      avatarSize: 36,
      avatarRadius: "50%",
      chevron: false,
      star: true,
      senderFont: 13,
      subjectFont: 12,
      previewFont: 11,
      rowPadding: "10px 12px",
      contentGap: 10,
    },
  },
  {
    id: "desktop-mail",
    name: "Mac Mail",
    subjectCharsJa: 28,
    subjectCharsEn: 52,
    previewCharsJa: 0,
    previewCharsEn: 0,
    senderChars: 20,
    type: "desktop",
    chrome: {
      unread: "dot",
      avatar: false,
      chevron: false,
      star: false,
      flag: true,
      senderFont: 12,
      subjectFont: 11,
      previewFont: 11,
      rowPadding: "8px 10px",
      contentGap: 8,
    },
  },
  {
    id: "desktop-gmail",
    name: "Gmail Desktop",
    subjectCharsJa: 35,
    subjectCharsEn: 65,
    previewCharsJa: 0,
    previewCharsEn: 0,
    senderChars: 20,
    type: "desktop",
    chrome: {
      unread: "bold",
      avatar: false,
      chevron: false,
      star: true,
      checkbox: true,
      layoutAuto: true,
      senderFont: 12,
      subjectFont: 11,
      previewFont: 11,
      rowPadding: "8px 10px",
      contentGap: 8,
    },
  },
  {
    id: "desktop-outlook",
    name: "Outlook Desktop",
    subjectCharsJa: 30,
    subjectCharsEn: 55,
    previewCharsJa: 35,
    previewCharsEn: 70,
    senderChars: 22,
    type: "desktop",
    chrome: {
      unread: "bar",
      avatar: true,
      avatarSize: 32,
      avatarRadius: "50%",
      chevron: false,
      star: false,
      flag: true,
      layoutAuto: true,
      senderFont: 12,
      subjectFont: 11,
      previewFont: 10,
      rowPadding: "8px 10px",
      contentGap: 8,
    },
  },
];

export const NOTIF_DEVICES = [
  {
    id: "iphone-lock",
    name: { ja: "iPhone ロック画面", en: "iPhone Lock Screen" },
    subjectCharsJa: 22,
    subjectCharsEn: 44,
    previewCharsJa: 28,
    previewCharsEn: 56,
    senderChars: 20,
  },
  {
    id: "android-notif",
    name: { ja: "Android 通知", en: "Android Notification" },
    subjectCharsJa: 24,
    subjectCharsEn: 48,
    previewCharsJa: 30,
    previewCharsEn: 60,
    senderChars: 22,
  },
];
